package columbo

import (
	"encoding/json"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/packages"
)

func TestProseCommentPolicy(t *testing.T) {
	h := &testHarness{T: t}
	source := "// Package fixture explains the package.\npackage fixture\n/* Keep this omission. */\nvar Value = 1 // inline explanation\n// F documents the function.\nfunc F(){\n// TODO keep this disabled\n/* println(Value) */\n}\n"
	dir := h.fixture(source)
	cfg := quiet()
	cfg.Severity[commentSmell] = "fail"
	report := h.investigate(dir, cfg)
	c := h.one(report, commentSmell)
	require.Equal(t, 1, report.Summary.Failed)
	require.Equal(t, 6, h.clueValue(c, "prose-comments"))
	require.Equal(t, 1, c.StartLine)
	require.Contains(t, strings.Join(c.Leads, " "), "regression test that fails when the unwanted behavior is introduced")
	require.Contains(t, strings.Join(c.Avoid, " "), "without first preserving")
	require.Equal(t, "fixture.<package-clause>", c.Symbol)
	require.Len(t, report.Declarations, 1)
	require.Equal(t, "package-clause", report.Declarations[0].Source.Kind)
	require.Equal(t, report, h.investigate(dir, cfg))
	path := filepath.Join(t.TempDir(), "comments.sqlite")
	require.NoError(t, WriteSnapshot(path, report, "test"))
	snapshot, err := OpenSnapshot(path)
	require.NoError(t, err)
	defer snapshot.Close()
	summary, code, err := RenderSnapshot(snapshot.Queries(), path)
	require.NoError(t, err)
	require.Equal(t, 1, code)
	require.Contains(t, string(summary), "prose-comment")
	cfg.Severity[commentSmell] = "warn"
	require.Equal(t, 1, h.investigate(dir, cfg).Summary.Warned)
	cfg.Severity[commentSmell] = "off"
	require.Empty(t, h.investigate(dir, cfg).Cases)
}

func TestMachineCommentRecognition(t *testing.T) {
	data, err := os.ReadFile("testdata/comment-directives.json")
	require.NoError(t, err)
	var samples struct{ Allowed, Rejected []string }
	require.NoError(t, json.Unmarshal(data, &samples))
	for _, text := range samples.Allowed {
		require.True(t, machineComment(text), text)
	}
	for _, text := range samples.Rejected {
		require.False(t, machineComment(text), text)
	}
}

func commentSource(t *testing.T, source string) *file {
	t.Helper()
	fs := token.NewFileSet()
	parsed, err := parser.ParseFile(fs, "source.go", source, parser.ParseComments)
	require.NoError(t, err)
	return &file{fset: fs, tf: fs.File(parsed.Pos()), ast: parsed, data: []byte(source), rel: "source.go", pkg: &packages.Package{PkgPath: "fixture"}}
}

func TestCommentReceiptsUsePhysicalBytes(t *testing.T) {
	source := "//line virtual.go:900\r\npackage fixture\r\n/* first\r\nsecond */\r\nvar URL = `https://host/*path*/` // last\r\n"
	f := commentSource(t, source)
	receipts := f.proseComments()
	require.Len(t, receipts, 2)
	require.Equal(t, 3, receipts[0].StartLine)
	require.Equal(t, 4, receipts[0].EndLine)
	require.Equal(t, "/* first\r\nsecond */", source[receipts[0].StartOffset:receipts[0].EndOffset])
	require.Equal(t, 5, receipts[1].StartLine)
	require.Equal(t, "// last\r", source[receipts[1].StartOffset:receipts[1].EndOffset])
}

func TestDirectiveDoesNotExemptAdjacentProse(t *testing.T) {
	f := commentSource(t, "package fixture\n// Preserve this behavior.\n//go:noinline\n// Another explanation.\nfunc F(){}\n")
	require.Len(t, f.proseComments(), 2)
}

func TestCgoPreambleIsMachineInput(t *testing.T) {
	for _, source := range []string{
		"package fixture\n/*\n#include <stdlib.h>\n*/\nimport \"C\"\n// actual prose\nvar Value int\n",
		"package fixture\nimport (\n// #include <stdlib.h>\n\"C\"\n)\n// actual prose\nvar Value int\n",
	} {
		f := commentSource(t, source)
		require.Len(t, f.proseComments(), 1)
	}
	f := commentSource(t, "package fixture\n/* #include <stdlib.h> */\nvar Value int\n")
	require.Len(t, f.proseComments(), 1)
}

func TestCommentScopeAndSuppression(t *testing.T) {
	h := &testHarness{T: t}
	cfg := quiet()
	cfg.Severity[commentSmell] = "fail"
	dir := h.fixture("package fixture\nvar URL = \"https://host//path\"\nvar Block = `/* not a comment */`\n")
	h.write(dir, "source_test.go", "package fixture\n// ignored test source\n")
	h.write(dir, "generated.go", "// Code generated by tool. DO NOT EDIT.\npackage fixture\n// generated explanation\n")
	h.write(dir, "excluded.go", "package fixture\n// excluded prose\n")
	cfg.Exclude = append(cfg.Exclude, "excluded.go")
	require.Empty(t, h.investigate(dir, cfg).Cases)
	h.write(dir, "source.go", "package fixture\n// columbo:ignore prose-comment -- should not waive this file\nfunc F(){}\n")
	_, err := Analyze(dir, []string{"./..."}, cfg)
	require.ErrorContains(t, err, "invalid columbo suppression")
}

func TestCommentDefaultAndStableIdentity(t *testing.T) {
	require.Equal(t, "fail", Defaults().Severity[commentSmell])
	h := &testHarness{T: t}
	cfg := quiet()
	cfg.Severity[commentSmell] = "fail"
	dir := h.fixture("package fixture\n// before\nvar Value int\n")
	first := h.one(h.investigate(dir, cfg), commentSmell)
	h.write(dir, "source.go", "package fixture\n\n\n// rewritten\nvar Value int\n// added\n")
	second := h.one(h.investigate(dir, cfg), commentSmell)
	require.Equal(t, first.ID, second.ID)
	require.NotEqual(t, first.StartLine, second.StartLine)
}
