package columbo

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/KellyBennett/Columbo/internal/snapshotdb"
	"github.com/stretchr/testify/require"
)

const duplicateFunction = `func NAME(items []int) int {
 total := len(items)
 total += 3
 total *= 2
 total -= 4
 total /= 2
 for _, item := range items {
  if item > 7 {
   total += item * 2
  } else {
   total -= item
  }
 }
 if total < 0 {
  return -total
 }
 return total
}
`

func duplicateFixture(name string) string {
	return "package fixture\n" + strings.ReplaceAll(duplicateFunction, "NAME", name)
}

func duplicateConfig() Config {
	c := quiet()
	c.Severity["duplicate-code"] = "warn"
	return c
}

func TestDuplicateGroupEvidenceAndRepeatability(t *testing.T) {
	h := &testHarness{T: t}
	dir := h.fixture(duplicateFixture("First"))
	h.write(dir, "second.go", strings.NewReplacer("NAME", "Second", "total", "sum", "7", "9").Replace("package fixture\n"+duplicateFunction))
	h.write(dir, "third.go", duplicateFixture("Third"))
	r := h.investigate(dir, duplicateConfig())
	c := h.one(r, "duplicate-code")
	require.Equal(t, "WARN", c.Verdict)
	require.Equal(t, 3, h.clueValue(c, "duplicate-fragments"))
	require.Len(t, c.Receipts, 3)
	require.Len(t, r.Declarations, 3)
	for _, receipt := range c.Receipts {
		s := receipt.(Source)
		require.Equal(t, "duplicate-fragment", s.Kind)
		data := h.read(filepath.Join(dir, s.File))
		require.Contains(t, string(data[s.StartOffset:s.EndOffset]), "func ")
	}
	require.Equal(t, canonical(r), canonical(h.investigate(dir, duplicateConfig())))
	db := h.snapshot(r)
	require.Equal(t, 6, h.sqlCount(db, "SELECT COUNT(*) FROM clue_receipts WHERE case_id=?", c.ID))
	queries := testDatabaseQueries(db)
	locations, err := queries.SummaryDuplicateFragments(t.Context(), snapshotdb.SummaryDuplicateFragmentsParams{CaseID: c.ID})
	require.NoError(t, err)
	require.Len(t, locations, 3)
	summary, exit, err := RenderSnapshot(queries, "report.sqlite")
	require.NoError(t, err)
	require.Zero(t, exit)
	require.Equal(t, 3, bytes.Count(summary, []byte("duplicate fragment ")))
}

func TestDuplicateScopeAndSeverity(t *testing.T) {
	h := &testHarness{T: t}
	dir := h.fixture(duplicateFixture("First"))
	h.write(dir, "second.go", duplicateFixture("Second"))
	c := duplicateConfig()
	c.Severity["duplicate-code"] = "fail"
	require.Equal(t, 1, h.investigate(dir, c).Summary.Failed)
	c.Counts["duplicate-tokens"] = 10000
	require.Empty(t, h.investigate(dir, c).Cases)
	c = duplicateConfig()
	c.Exclude = append(c.Exclude, "second.go")
	require.Empty(t, h.investigate(dir, c).Cases)
	h.write(dir, "second.go", "// Code generated by fixture. DO NOT EDIT.\n"+duplicateFixture("Second"))
	require.Empty(t, h.investigate(dir, duplicateConfig()).Cases)
	h.write(dir, "second.go", duplicateFixture("Second"))
	c = duplicateConfig()
	c.Severity["duplicate-code"] = "off"
	require.Empty(t, h.investigate(dir, c).Cases)
}

func TestDuplicateConfiguration(t *testing.T) {
	require.Equal(t, "warn", Defaults().Severity["duplicate-code"])
	c, err := decodeConfig([]byte("severity:\n  duplicate-code: fail\nthresholds:\n  duplicate-tokens: 100\n"), Defaults())
	require.NoError(t, err)
	require.EqualValues(t, 100, c.Counts["duplicate-tokens"])
	require.Equal(t, "fail", c.Severity["duplicate-code"])
	_, err = decodeConfig([]byte("thresholds:\n  duplicate-tokens: 0\n"), Defaults())
	require.Error(t, err)
}

func TestDuplicateAnchorSuppression(t *testing.T) {
	h := &testHarness{T: t}
	dir := h.fixture("package fixture\n// columbo:ignore duplicate-code -- independent policy copy retained deliberately\n" + strings.ReplaceAll(duplicateFunction, "NAME", "First"))
	h.write(dir, "zcopy.go", duplicateFixture("Second"))
	r := h.investigate(dir, duplicateConfig())
	require.Equal(t, 1, r.Summary.Suppressed)
	require.Equal(t, 0, r.Summary.Warned)
	require.True(t, r.Suppressions[0].Applied)
}

func TestDuplicateSameFileAndThresholdBoundary(t *testing.T) {
	h := &testHarness{T: t}
	source := duplicateFixture("First") + strings.ReplaceAll(duplicateFunction, "NAME", "Second")
	dir := h.fixture(source)
	c := duplicateConfig()
	first := h.one(h.investigate(dir, c), "duplicate-code")
	tokens := h.clueValue(first, "duplicate-tokens").(int)
	c.Counts["duplicate-tokens"] = int64(tokens)
	require.Equal(t, first.ID, h.one(h.investigate(dir, c), "duplicate-code").ID)
	c.Counts["duplicate-tokens"] = int64(tokens + 1)
	require.Empty(t, h.investigate(dir, c).Cases)
	h.write(dir, "source.go", "package fixture\n\n// shifted\n"+strings.TrimPrefix(source, "package fixture\n"))
	require.Equal(t, first.ID, h.one(h.investigate(dir, duplicateConfig()), "duplicate-code").ID)
}

func TestDuplicateSelectedPackagesAndTests(t *testing.T) {
	h := &testHarness{T: t}
	dir := h.fixture(duplicateFixture("First"))
	h.write(dir, "copy_test.go", duplicateFixture("TestCopy"))
	require.Empty(t, h.investigate(dir, duplicateConfig()).Cases)
	require.NoError(t, os.Mkdir(filepath.Join(dir, "other"), 0700))
	h.write(dir, "other/copy.go", duplicateFixture("Other"))
	report, err := Analyze(dir, []string{"."}, duplicateConfig())
	require.NoError(t, err)
	require.Empty(t, report.Cases)
	require.Len(t, h.investigate(dir, duplicateConfig()).Cases, 1)
}
