// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package snapshotdb

type Case struct {
	ID                   string
	Ordinal              int64
	PrimaryDeclarationID int64
	Smell                string
	Verdict              string
	Suppressed           int64
	StartLine            int64
	EndLine              int64
	Why                  string
	Diagnosis            string
}

type CaseDeclaration struct {
	CaseID        string
	DeclarationID int64
	Role          string
}

type CaseGuidance struct {
	CaseID  string
	Kind    string
	Ordinal int64
	Item    string
}

type CaseHistory struct {
	CaseID     string
	Ordinal    int64
	CommitHash string
	Kind       string
}

type CaseHistoryFile struct {
	CaseID         string
	HistoryOrdinal int64
	Ordinal        int64
	FileID         int64
}

type CasePolicyReview struct {
	CaseID   string
	Ordinal  int64
	PolicyID string
}

type Clue struct {
	ID                int64
	CaseID            string
	Ordinal           int64
	Kind              string
	Subject           string
	ValueType         string
	NumericValue      interface{}
	LimitType         *string
	LimitValue        interface{}
	Operator          *string
	DeclarationID     *int64
	ClusterID         *int64
	MemberID          *int64
	PairLeftMemberID  *int64
	PairRightMemberID *int64
}

type ClueReceipt struct {
	CaseID    string
	ClueID    int64
	ReceiptID int64
}

type ClueValue struct {
	ClueID  int64
	Ordinal int64
	Value   string
}

type Cluster struct {
	ID                 int64
	CaseID             string
	ClusterKey         string
	OwnerDeclarationID int64
	FileID             int64
	Ordinal            int64
}

type ClusterMember struct {
	ID                  int64
	ClusterID           int64
	CaseID              string
	HelperDeclarationID int64
	Ordinal             int64
	CallOffset          int64
}

type Commit struct {
	Hash        string
	CommittedAt int64
}

type Correlation struct {
	ID            string
	Kind          string
	Confidence    string
	VariantDomain string
	Diagnosis     string
	PolicyID      string
	PolicyStatus  string
	PolicyNote    string
	ReviewPrompt  string
}

type CorrelationCase struct {
	CorrelationID string
	CaseID        string
}

type CorrelationEvidence struct {
	CorrelationID string
	CaseID        string
	ReceiptID     int64
}

type CorrelationGuidance struct {
	CorrelationID string
	Kind          string
	Ordinal       int64
	Text          string
}

type CorrelationRoleCandidate struct {
	CorrelationID string
	CandidateID   string
}

type Declaration struct {
	ID          int64
	FileID      int64
	Symbol      string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
}

type DeclarationDependency struct {
	DeclarationID int64
	DependencyID  int64
	Scored        int64
}

type Dependency struct {
	ID       int64
	Identity string
}

type DependencyReceipt struct {
	DeclarationID int64
	DependencyID  int64
	ReceiptID     int64
	CaseID        string
}

type File struct {
	ID   int64
	Path string
}

type PolicyReview struct {
	ID           string
	Note         string
	ReviewPrompt string
}

type ReceiptExpansionDeclaration struct {
	ReceiptID     int64
	Ordinal       int64
	DeclarationID int64
	Symbol        string
}

type ReceiptExpansionSite struct {
	ReceiptID          int64
	Ordinal            int64
	FileID             int64
	CallOffset         int64
	OwnerDeclarationID *int64
}

type Report struct {
	ID             int64
	SchemaVersion  int64
	ColumboVersion string
}

type RoleCandidate struct {
	ID                 string
	CanonicalInterface string
	Confidence         string
	Classification     string
}

type RoleCandidateCaseLink struct {
	CandidateID string
	CaseID      string
}

type RoleCandidateImplementation struct {
	CandidateID string
	Identity    string
}

type RoleCandidateInterface struct {
	CandidateID  string
	Identity     string
	Relationship string
}

type RoleCandidateMessage struct {
	CandidateID string
	Identity    string
}

type RoleCandidateReceipt struct {
	CandidateID   string
	Ordinal       int64
	DeclarationID int64
	Kind          string
	Subject       string
	Message       string
	StartLine     int64
	EndLine       int64
	StartOffset   int64
	EndOffset     int64
}

type SourceReceipt struct {
	ID                  int64
	CaseID              string
	Ordinal             int64
	Kind                string
	FileID              int64
	StartLine           int64
	EndLine             int64
	StartOffset         int64
	EndOffset           int64
	Subject             string
	ValueType           *string
	Value               interface{}
	Nesting             *int64
	SourceDeclarationID *int64
	Spelling            string
}

type Summary struct {
	Failed     interface{}
	Warned     interface{}
	Suppressed interface{}
}

type Suppression struct {
	ID            int64
	Ordinal       int64
	Smell         string
	Symbol        string
	FileID        int64
	Line          int64
	Justification string
	Applied       int64
	CaseID        *string
}

type Warning struct {
	ID      int64
	Ordinal int64
	Code    string
	FileID  *int64
	Line    int64
	Message string
}
