// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package snapshotdb

import (
	"context"
)

type Querier interface {
	DependencyScored(ctx context.Context, arg DependencyScoredParams) (int64, error)
	InsertCase(ctx context.Context, arg InsertCaseParams) error
	InsertClue(ctx context.Context, arg InsertClueParams) (int64, error)
	InsertClueValue(ctx context.Context, arg InsertClueValueParams) error
	InsertCluster(ctx context.Context, arg InsertClusterParams) (int64, error)
	InsertClusterMember(ctx context.Context, arg InsertClusterMemberParams) (int64, error)
	InsertCommit(ctx context.Context, arg InsertCommitParams) error
	InsertDeclaration(ctx context.Context, arg InsertDeclarationParams) (int64, error)
	InsertDeclarationDependency(ctx context.Context, arg InsertDeclarationDependencyParams) error
	InsertDependency(ctx context.Context, arg InsertDependencyParams) (int64, error)
	InsertDependencyReceipt(ctx context.Context, arg InsertDependencyReceiptParams) error
	InsertExpansionDeclaration(ctx context.Context, arg InsertExpansionDeclarationParams) error
	InsertExpansionSite(ctx context.Context, arg InsertExpansionSiteParams) error
	InsertFile(ctx context.Context, arg InsertFileParams) (int64, error)
	InsertGuidance(ctx context.Context, arg InsertGuidanceParams) error
	InsertHistory(ctx context.Context, arg InsertHistoryParams) error
	InsertHistoryFile(ctx context.Context, arg InsertHistoryFileParams) error
	InsertPolicy(ctx context.Context, arg InsertPolicyParams) error
	InsertReport(ctx context.Context, arg InsertReportParams) error
	InsertRoleCandidate(ctx context.Context, arg InsertRoleCandidateParams) error
	InsertRoleImplementation(ctx context.Context, arg InsertRoleImplementationParams) error
	InsertRoleInterface(ctx context.Context, arg InsertRoleInterfaceParams) error
	InsertRoleMessage(ctx context.Context, arg InsertRoleMessageParams) error
	InsertRoleReceipt(ctx context.Context, arg InsertRoleReceiptParams) error
	InsertSourceReceipt(ctx context.Context, arg InsertSourceReceiptParams) (int64, error)
	InsertSuppression(ctx context.Context, arg InsertSuppressionParams) error
	InsertWarning(ctx context.Context, arg InsertWarningParams) error
	LinkCaseDeclaration(ctx context.Context, arg LinkCaseDeclarationParams) error
	LinkClueReceipt(ctx context.Context, arg LinkClueReceiptParams) error
	LinkPolicy(ctx context.Context, arg LinkPolicyParams) error
	LinkRoleCase(ctx context.Context, arg LinkRoleCaseParams) error
	ReportIdentity(ctx context.Context) (ReportIdentityRow, error)
	SummaryCases(ctx context.Context) ([]SummaryCasesRow, error)
	SummaryClueSets(ctx context.Context, arg SummaryClueSetsParams) ([]SummaryClueSetsRow, error)
	SummaryDuplicateFragments(ctx context.Context, arg SummaryDuplicateFragmentsParams) ([]SummaryDuplicateFragmentsRow, error)
	SummaryMetrics(ctx context.Context, arg SummaryMetricsParams) ([]SummaryMetricsRow, error)
	SummaryPolicy(ctx context.Context, arg SummaryPolicyParams) ([]PolicyReview, error)
	SummaryRoleInterfaces(ctx context.Context, arg SummaryRoleInterfacesParams) ([]SummaryRoleInterfacesRow, error)
	SummaryRoles(ctx context.Context) ([]RoleCandidate, error)
	SummarySelectionReceipts(ctx context.Context, arg SummarySelectionReceiptsParams) ([]SummarySelectionReceiptsRow, error)
	SummarySuppressions(ctx context.Context, arg SummarySuppressionsParams) ([]SummarySuppressionsRow, error)
	SummaryTotals(ctx context.Context) (SummaryTotalsRow, error)
	SummaryVariantDecisions(ctx context.Context, arg SummaryVariantDecisionsParams) ([]SummaryVariantDecisionsRow, error)
	SummaryWarnings(ctx context.Context) ([]SummaryWarningsRow, error)
	WarningMessages(ctx context.Context) ([]string, error)
}

var _ Querier = (*Queries)(nil)
