// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package snapshotdb

import (
	"context"
)

const advisoryCoverage = `-- name: AdvisoryCoverage :many
SELECT kind,files_analyzed,declarations_analyzed FROM advisory_collectors ORDER BY kind
`

func (q *Queries) AdvisoryCoverage(ctx context.Context) ([]AdvisoryCollector, error) {
	rows, err := q.db.QueryContext(ctx, advisoryCoverage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvisoryCollector
	for rows.Next() {
		var i AdvisoryCollector
		if err := rows.Scan(&i.Kind, &i.FilesAnalyzed, &i.DeclarationsAnalyzed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advisoryReceipts = `-- name: AdvisoryReceipts :many
SELECT kind,subject,start_line,end_line,start_offset,end_offset,spelling FROM advisory_receipts WHERE group_id=? AND site_ordinal=? ORDER BY ordinal
`

type AdvisoryReceiptsParams struct {
	GroupID     string
	SiteOrdinal int64
}

type AdvisoryReceiptsRow struct {
	Kind        string
	Subject     string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
	Spelling    string
}

func (q *Queries) AdvisoryReceipts(ctx context.Context, arg AdvisoryReceiptsParams) ([]AdvisoryReceiptsRow, error) {
	rows, err := q.db.QueryContext(ctx, advisoryReceipts, arg.GroupID, arg.SiteOrdinal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvisoryReceiptsRow
	for rows.Next() {
		var i AdvisoryReceiptsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Subject,
			&i.StartLine,
			&i.EndLine,
			&i.StartOffset,
			&i.EndOffset,
			&i.Spelling,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advisorySites = `-- name: AdvisorySites :many
SELECT s.ordinal,s.representation,s.input_expression,d.symbol,f.path FROM advisory_sites s JOIN declarations d ON d.id=s.declaration_id JOIN files f ON f.id=d.file_id WHERE s.group_id=? ORDER BY s.ordinal
`

type AdvisorySitesParams struct {
	GroupID string
}

type AdvisorySitesRow struct {
	Ordinal         int64
	Representation  string
	InputExpression string
	Symbol          string
	Path            string
}

func (q *Queries) AdvisorySites(ctx context.Context, arg AdvisorySitesParams) ([]AdvisorySitesRow, error) {
	rows, err := q.db.QueryContext(ctx, advisorySites, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvisorySitesRow
	for rows.Next() {
		var i AdvisorySitesRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.Representation,
			&i.InputExpression,
			&i.Symbol,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advisoryValues = `-- name: AdvisoryValues :many
SELECT kind,identity,value FROM advisory_values WHERE group_id=? ORDER BY kind,ordinal
`

type AdvisoryValuesParams struct {
	GroupID string
}

type AdvisoryValuesRow struct {
	Kind     string
	Identity string
	Value    string
}

func (q *Queries) AdvisoryValues(ctx context.Context, arg AdvisoryValuesParams) ([]AdvisoryValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, advisoryValues, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvisoryValuesRow
	for rows.Next() {
		var i AdvisoryValuesRow
		if err := rows.Scan(&i.Kind, &i.Identity, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dependencyScored = `-- name: DependencyScored :one
SELECT scored FROM declaration_dependencies WHERE declaration_id=? AND dependency_id=?
`

type DependencyScoredParams struct {
	DeclarationID int64
	DependencyID  int64
}

func (q *Queries) DependencyScored(ctx context.Context, arg DependencyScoredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dependencyScored, arg.DeclarationID, arg.DependencyID)
	var scored int64
	err := row.Scan(&scored)
	return scored, err
}

const insertAdvisoryCollector = `-- name: InsertAdvisoryCollector :exec
INSERT INTO advisory_collectors(kind,files_analyzed,declarations_analyzed) VALUES (?,?,?)
`

type InsertAdvisoryCollectorParams struct {
	Kind                 string
	FilesAnalyzed        int64
	DeclarationsAnalyzed int64
}

func (q *Queries) InsertAdvisoryCollector(ctx context.Context, arg InsertAdvisoryCollectorParams) error {
	_, err := q.db.ExecContext(ctx, insertAdvisoryCollector, arg.Kind, arg.FilesAnalyzed, arg.DeclarationsAnalyzed)
	return err
}

const insertAdvisoryGroup = `-- name: InsertAdvisoryGroup :exec
INSERT INTO advisory_groups(id,kind,subject,lead,limits) VALUES (?,?,?,?,?)
`

type InsertAdvisoryGroupParams struct {
	ID      string
	Kind    string
	Subject string
	Lead    string
	Limits  string
}

func (q *Queries) InsertAdvisoryGroup(ctx context.Context, arg InsertAdvisoryGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertAdvisoryGroup,
		arg.ID,
		arg.Kind,
		arg.Subject,
		arg.Lead,
		arg.Limits,
	)
	return err
}

const insertAdvisoryReceipt = `-- name: InsertAdvisoryReceipt :exec
INSERT INTO advisory_receipts(group_id,site_ordinal,ordinal,kind,subject,start_line,end_line,start_offset,end_offset,spelling) VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertAdvisoryReceiptParams struct {
	GroupID     string
	SiteOrdinal int64
	Ordinal     int64
	Kind        string
	Subject     string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
	Spelling    string
}

func (q *Queries) InsertAdvisoryReceipt(ctx context.Context, arg InsertAdvisoryReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertAdvisoryReceipt,
		arg.GroupID,
		arg.SiteOrdinal,
		arg.Ordinal,
		arg.Kind,
		arg.Subject,
		arg.StartLine,
		arg.EndLine,
		arg.StartOffset,
		arg.EndOffset,
		arg.Spelling,
	)
	return err
}

const insertAdvisorySite = `-- name: InsertAdvisorySite :exec
INSERT INTO advisory_sites(group_id,ordinal,declaration_id,representation,input_expression) VALUES (?,?,?,?,?)
`

type InsertAdvisorySiteParams struct {
	GroupID         string
	Ordinal         int64
	DeclarationID   int64
	Representation  string
	InputExpression string
}

func (q *Queries) InsertAdvisorySite(ctx context.Context, arg InsertAdvisorySiteParams) error {
	_, err := q.db.ExecContext(ctx, insertAdvisorySite,
		arg.GroupID,
		arg.Ordinal,
		arg.DeclarationID,
		arg.Representation,
		arg.InputExpression,
	)
	return err
}

const insertAdvisorySiteValue = `-- name: InsertAdvisorySiteValue :exec
INSERT INTO advisory_site_values(group_id,site_ordinal,ordinal,identity,value) VALUES (?,?,?,?,?)
`

type InsertAdvisorySiteValueParams struct {
	GroupID     string
	SiteOrdinal int64
	Ordinal     int64
	Identity    string
	Value       string
}

func (q *Queries) InsertAdvisorySiteValue(ctx context.Context, arg InsertAdvisorySiteValueParams) error {
	_, err := q.db.ExecContext(ctx, insertAdvisorySiteValue,
		arg.GroupID,
		arg.SiteOrdinal,
		arg.Ordinal,
		arg.Identity,
		arg.Value,
	)
	return err
}

const insertAdvisoryValue = `-- name: InsertAdvisoryValue :exec
INSERT INTO advisory_values(group_id,kind,ordinal,identity,value) VALUES (?,?,?,?,?)
`

type InsertAdvisoryValueParams struct {
	GroupID  string
	Kind     string
	Ordinal  int64
	Identity string
	Value    string
}

func (q *Queries) InsertAdvisoryValue(ctx context.Context, arg InsertAdvisoryValueParams) error {
	_, err := q.db.ExecContext(ctx, insertAdvisoryValue,
		arg.GroupID,
		arg.Kind,
		arg.Ordinal,
		arg.Identity,
		arg.Value,
	)
	return err
}

const insertCase = `-- name: InsertCase :exec
INSERT INTO cases(id,ordinal,primary_declaration_id,smell,verdict,suppressed,start_line,end_line,why,diagnosis) VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertCaseParams struct {
	ID                   string
	Ordinal              int64
	PrimaryDeclarationID int64
	Smell                string
	Verdict              string
	Suppressed           int64
	StartLine            int64
	EndLine              int64
	Why                  string
	Diagnosis            string
}

func (q *Queries) InsertCase(ctx context.Context, arg InsertCaseParams) error {
	_, err := q.db.ExecContext(ctx, insertCase,
		arg.ID,
		arg.Ordinal,
		arg.PrimaryDeclarationID,
		arg.Smell,
		arg.Verdict,
		arg.Suppressed,
		arg.StartLine,
		arg.EndLine,
		arg.Why,
		arg.Diagnosis,
	)
	return err
}

const insertClue = `-- name: InsertClue :execlastid
INSERT INTO clues(case_id,ordinal,kind,subject,value_type,numeric_value,limit_type,limit_value,operator,declaration_id,cluster_id,member_id,pair_left_member_id,pair_right_member_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertClueParams struct {
	CaseID            string
	Ordinal           int64
	Kind              string
	Subject           string
	ValueType         string
	NumericValue      interface{}
	LimitType         *string
	LimitValue        interface{}
	Operator          *string
	DeclarationID     *int64
	ClusterID         *int64
	MemberID          *int64
	PairLeftMemberID  *int64
	PairRightMemberID *int64
}

func (q *Queries) InsertClue(ctx context.Context, arg InsertClueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertClue,
		arg.CaseID,
		arg.Ordinal,
		arg.Kind,
		arg.Subject,
		arg.ValueType,
		arg.NumericValue,
		arg.LimitType,
		arg.LimitValue,
		arg.Operator,
		arg.DeclarationID,
		arg.ClusterID,
		arg.MemberID,
		arg.PairLeftMemberID,
		arg.PairRightMemberID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertClueValue = `-- name: InsertClueValue :exec
INSERT INTO clue_values(clue_id,ordinal,value) VALUES (?,?,?)
`

type InsertClueValueParams struct {
	ClueID  int64
	Ordinal int64
	Value   string
}

func (q *Queries) InsertClueValue(ctx context.Context, arg InsertClueValueParams) error {
	_, err := q.db.ExecContext(ctx, insertClueValue, arg.ClueID, arg.Ordinal, arg.Value)
	return err
}

const insertCluster = `-- name: InsertCluster :execlastid
INSERT INTO clusters(case_id,cluster_key,owner_declaration_id,file_id,ordinal) VALUES (?,?,?,?,?)
`

type InsertClusterParams struct {
	CaseID             string
	ClusterKey         string
	OwnerDeclarationID int64
	FileID             int64
	Ordinal            int64
}

func (q *Queries) InsertCluster(ctx context.Context, arg InsertClusterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCluster,
		arg.CaseID,
		arg.ClusterKey,
		arg.OwnerDeclarationID,
		arg.FileID,
		arg.Ordinal,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertClusterMember = `-- name: InsertClusterMember :execlastid
INSERT INTO cluster_members(cluster_id,case_id,helper_declaration_id,ordinal,call_offset) VALUES (?,?,?,?,?)
`

type InsertClusterMemberParams struct {
	ClusterID           int64
	CaseID              string
	HelperDeclarationID int64
	Ordinal             int64
	CallOffset          int64
}

func (q *Queries) InsertClusterMember(ctx context.Context, arg InsertClusterMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertClusterMember,
		arg.ClusterID,
		arg.CaseID,
		arg.HelperDeclarationID,
		arg.Ordinal,
		arg.CallOffset,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertCommit = `-- name: InsertCommit :exec
INSERT INTO commits(hash,committed_at) VALUES (?,?)
`

type InsertCommitParams struct {
	Hash        string
	CommittedAt int64
}

func (q *Queries) InsertCommit(ctx context.Context, arg InsertCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertCommit, arg.Hash, arg.CommittedAt)
	return err
}

const insertCorrelation = `-- name: InsertCorrelation :exec
INSERT INTO correlations (id,kind,confidence,variant_domain,diagnosis,policy_id,policy_status,policy_note,review_prompt) VALUES (?,?,?,?,?,?,?,?,?)
`

type InsertCorrelationParams struct {
	ID            string
	Kind          string
	Confidence    string
	VariantDomain string
	Diagnosis     string
	PolicyID      string
	PolicyStatus  string
	PolicyNote    string
	ReviewPrompt  string
}

func (q *Queries) InsertCorrelation(ctx context.Context, arg InsertCorrelationParams) error {
	_, err := q.db.ExecContext(ctx, insertCorrelation,
		arg.ID,
		arg.Kind,
		arg.Confidence,
		arg.VariantDomain,
		arg.Diagnosis,
		arg.PolicyID,
		arg.PolicyStatus,
		arg.PolicyNote,
		arg.ReviewPrompt,
	)
	return err
}

const insertCorrelationGuidance = `-- name: InsertCorrelationGuidance :exec
INSERT INTO correlation_guidance (correlation_id,kind,ordinal,text) VALUES (?,?,?,?)
`

type InsertCorrelationGuidanceParams struct {
	CorrelationID string
	Kind          string
	Ordinal       int64
	Text          string
}

func (q *Queries) InsertCorrelationGuidance(ctx context.Context, arg InsertCorrelationGuidanceParams) error {
	_, err := q.db.ExecContext(ctx, insertCorrelationGuidance,
		arg.CorrelationID,
		arg.Kind,
		arg.Ordinal,
		arg.Text,
	)
	return err
}

const insertDeclaration = `-- name: InsertDeclaration :execlastid
INSERT INTO declarations(file_id,symbol,start_line,end_line,start_offset,end_offset) VALUES (?,?,?,?,?,?)
`

type InsertDeclarationParams struct {
	FileID      int64
	Symbol      string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
}

func (q *Queries) InsertDeclaration(ctx context.Context, arg InsertDeclarationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDeclaration,
		arg.FileID,
		arg.Symbol,
		arg.StartLine,
		arg.EndLine,
		arg.StartOffset,
		arg.EndOffset,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertDeclarationDependency = `-- name: InsertDeclarationDependency :exec
INSERT INTO declaration_dependencies(declaration_id,dependency_id,scored) VALUES (?,?,?)
`

type InsertDeclarationDependencyParams struct {
	DeclarationID int64
	DependencyID  int64
	Scored        int64
}

func (q *Queries) InsertDeclarationDependency(ctx context.Context, arg InsertDeclarationDependencyParams) error {
	_, err := q.db.ExecContext(ctx, insertDeclarationDependency, arg.DeclarationID, arg.DependencyID, arg.Scored)
	return err
}

const insertDependency = `-- name: InsertDependency :execlastid
INSERT INTO dependencies(identity) VALUES (?)
`

type InsertDependencyParams struct {
	Identity string
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDependency, arg.Identity)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertDependencyReceipt = `-- name: InsertDependencyReceipt :exec
INSERT INTO dependency_receipts(declaration_id,dependency_id,receipt_id,case_id) VALUES (?,?,?,?)
`

type InsertDependencyReceiptParams struct {
	DeclarationID int64
	DependencyID  int64
	ReceiptID     int64
	CaseID        string
}

func (q *Queries) InsertDependencyReceipt(ctx context.Context, arg InsertDependencyReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertDependencyReceipt,
		arg.DeclarationID,
		arg.DependencyID,
		arg.ReceiptID,
		arg.CaseID,
	)
	return err
}

const insertExpansionDeclaration = `-- name: InsertExpansionDeclaration :exec
INSERT INTO receipt_expansion_declarations(receipt_id,ordinal,declaration_id,symbol) VALUES (?,?,?,?)
`

type InsertExpansionDeclarationParams struct {
	ReceiptID     int64
	Ordinal       int64
	DeclarationID int64
	Symbol        string
}

func (q *Queries) InsertExpansionDeclaration(ctx context.Context, arg InsertExpansionDeclarationParams) error {
	_, err := q.db.ExecContext(ctx, insertExpansionDeclaration,
		arg.ReceiptID,
		arg.Ordinal,
		arg.DeclarationID,
		arg.Symbol,
	)
	return err
}

const insertExpansionSite = `-- name: InsertExpansionSite :exec
INSERT INTO receipt_expansion_sites(receipt_id,ordinal,file_id,call_offset,owner_declaration_id) VALUES (?,?,?,?,?)
`

type InsertExpansionSiteParams struct {
	ReceiptID          int64
	Ordinal            int64
	FileID             int64
	CallOffset         int64
	OwnerDeclarationID *int64
}

func (q *Queries) InsertExpansionSite(ctx context.Context, arg InsertExpansionSiteParams) error {
	_, err := q.db.ExecContext(ctx, insertExpansionSite,
		arg.ReceiptID,
		arg.Ordinal,
		arg.FileID,
		arg.CallOffset,
		arg.OwnerDeclarationID,
	)
	return err
}

const insertFile = `-- name: InsertFile :execlastid
INSERT INTO files(path) VALUES (?)
`

type InsertFileParams struct {
	Path string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertFile, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertGuidance = `-- name: InsertGuidance :exec
INSERT INTO case_guidance(case_id,kind,ordinal,item) VALUES (?,?,?,?)
`

type InsertGuidanceParams struct {
	CaseID  string
	Kind    string
	Ordinal int64
	Item    string
}

func (q *Queries) InsertGuidance(ctx context.Context, arg InsertGuidanceParams) error {
	_, err := q.db.ExecContext(ctx, insertGuidance,
		arg.CaseID,
		arg.Kind,
		arg.Ordinal,
		arg.Item,
	)
	return err
}

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO case_history(case_id,ordinal,commit_hash,kind) VALUES (?,?,?,?)
`

type InsertHistoryParams struct {
	CaseID     string
	Ordinal    int64
	CommitHash string
	Kind       string
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertHistory,
		arg.CaseID,
		arg.Ordinal,
		arg.CommitHash,
		arg.Kind,
	)
	return err
}

const insertHistoryFile = `-- name: InsertHistoryFile :exec
INSERT INTO case_history_files(case_id,history_ordinal,ordinal,file_id) VALUES (?,?,?,?)
`

type InsertHistoryFileParams struct {
	CaseID         string
	HistoryOrdinal int64
	Ordinal        int64
	FileID         int64
}

func (q *Queries) InsertHistoryFile(ctx context.Context, arg InsertHistoryFileParams) error {
	_, err := q.db.ExecContext(ctx, insertHistoryFile,
		arg.CaseID,
		arg.HistoryOrdinal,
		arg.Ordinal,
		arg.FileID,
	)
	return err
}

const insertPolicy = `-- name: InsertPolicy :exec
INSERT INTO policy_reviews(id,note,review_prompt) VALUES (?,?,?)
`

type InsertPolicyParams struct {
	ID           string
	Note         string
	ReviewPrompt string
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) error {
	_, err := q.db.ExecContext(ctx, insertPolicy, arg.ID, arg.Note, arg.ReviewPrompt)
	return err
}

const insertReport = `-- name: InsertReport :exec
INSERT INTO report(id,schema_version,columbo_version) VALUES (1, ?, ?)
`

type InsertReportParams struct {
	SchemaVersion  int64
	ColumboVersion string
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.ExecContext(ctx, insertReport, arg.SchemaVersion, arg.ColumboVersion)
	return err
}

const insertRoleCandidate = `-- name: InsertRoleCandidate :exec
INSERT INTO role_candidates (id,canonical_interface,confidence,classification) VALUES (?,?,?,?)
`

type InsertRoleCandidateParams struct {
	ID                 string
	CanonicalInterface string
	Confidence         string
	Classification     string
}

func (q *Queries) InsertRoleCandidate(ctx context.Context, arg InsertRoleCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertRoleCandidate,
		arg.ID,
		arg.CanonicalInterface,
		arg.Confidence,
		arg.Classification,
	)
	return err
}

const insertRoleImplementation = `-- name: InsertRoleImplementation :exec
INSERT INTO role_candidate_implementations (candidate_id,identity) VALUES (?,?)
`

type InsertRoleImplementationParams struct {
	CandidateID string
	Identity    string
}

func (q *Queries) InsertRoleImplementation(ctx context.Context, arg InsertRoleImplementationParams) error {
	_, err := q.db.ExecContext(ctx, insertRoleImplementation, arg.CandidateID, arg.Identity)
	return err
}

const insertRoleInterface = `-- name: InsertRoleInterface :exec
INSERT INTO role_candidate_interfaces (candidate_id,identity,relationship) VALUES (?,?,?)
`

type InsertRoleInterfaceParams struct {
	CandidateID  string
	Identity     string
	Relationship string
}

func (q *Queries) InsertRoleInterface(ctx context.Context, arg InsertRoleInterfaceParams) error {
	_, err := q.db.ExecContext(ctx, insertRoleInterface, arg.CandidateID, arg.Identity, arg.Relationship)
	return err
}

const insertRoleMessage = `-- name: InsertRoleMessage :exec
INSERT INTO role_candidate_messages (candidate_id,identity) VALUES (?,?)
`

type InsertRoleMessageParams struct {
	CandidateID string
	Identity    string
}

func (q *Queries) InsertRoleMessage(ctx context.Context, arg InsertRoleMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertRoleMessage, arg.CandidateID, arg.Identity)
	return err
}

const insertRoleReceipt = `-- name: InsertRoleReceipt :exec
INSERT INTO role_candidate_receipts (candidate_id,ordinal,declaration_id,kind,subject,message,start_line,end_line,start_offset,end_offset) VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertRoleReceiptParams struct {
	CandidateID   string
	Ordinal       int64
	DeclarationID int64
	Kind          string
	Subject       string
	Message       string
	StartLine     int64
	EndLine       int64
	StartOffset   int64
	EndOffset     int64
}

func (q *Queries) InsertRoleReceipt(ctx context.Context, arg InsertRoleReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertRoleReceipt,
		arg.CandidateID,
		arg.Ordinal,
		arg.DeclarationID,
		arg.Kind,
		arg.Subject,
		arg.Message,
		arg.StartLine,
		arg.EndLine,
		arg.StartOffset,
		arg.EndOffset,
	)
	return err
}

const insertSourceReceipt = `-- name: InsertSourceReceipt :execlastid
INSERT INTO source_receipts(case_id,ordinal,kind,file_id,start_line,end_line,start_offset,end_offset,subject,value_type,value,nesting,source_declaration_id,spelling) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertSourceReceiptParams struct {
	CaseID              string
	Ordinal             int64
	Kind                string
	FileID              int64
	StartLine           int64
	EndLine             int64
	StartOffset         int64
	EndOffset           int64
	Subject             string
	ValueType           *string
	Value               interface{}
	Nesting             *int64
	SourceDeclarationID *int64
	Spelling            string
}

func (q *Queries) InsertSourceReceipt(ctx context.Context, arg InsertSourceReceiptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSourceReceipt,
		arg.CaseID,
		arg.Ordinal,
		arg.Kind,
		arg.FileID,
		arg.StartLine,
		arg.EndLine,
		arg.StartOffset,
		arg.EndOffset,
		arg.Subject,
		arg.ValueType,
		arg.Value,
		arg.Nesting,
		arg.SourceDeclarationID,
		arg.Spelling,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertSuppression = `-- name: InsertSuppression :exec
INSERT INTO suppressions(ordinal,smell,symbol,file_id,line,justification,applied,case_id) VALUES (?,?,?,?,?,?,?,?)
`

type InsertSuppressionParams struct {
	Ordinal       int64
	Smell         string
	Symbol        string
	FileID        int64
	Line          int64
	Justification string
	Applied       int64
	CaseID        *string
}

func (q *Queries) InsertSuppression(ctx context.Context, arg InsertSuppressionParams) error {
	_, err := q.db.ExecContext(ctx, insertSuppression,
		arg.Ordinal,
		arg.Smell,
		arg.Symbol,
		arg.FileID,
		arg.Line,
		arg.Justification,
		arg.Applied,
		arg.CaseID,
	)
	return err
}

const insertWarning = `-- name: InsertWarning :exec
INSERT INTO warnings(ordinal,code,file_id,line,message) VALUES (?,?,?,?,?)
`

type InsertWarningParams struct {
	Ordinal int64
	Code    string
	FileID  *int64
	Line    int64
	Message string
}

func (q *Queries) InsertWarning(ctx context.Context, arg InsertWarningParams) error {
	_, err := q.db.ExecContext(ctx, insertWarning,
		arg.Ordinal,
		arg.Code,
		arg.FileID,
		arg.Line,
		arg.Message,
	)
	return err
}

const linkCaseDeclaration = `-- name: LinkCaseDeclaration :exec
INSERT OR IGNORE INTO case_declarations(case_id,declaration_id,role) VALUES (?,?,?)
`

type LinkCaseDeclarationParams struct {
	CaseID        string
	DeclarationID int64
	Role          string
}

func (q *Queries) LinkCaseDeclaration(ctx context.Context, arg LinkCaseDeclarationParams) error {
	_, err := q.db.ExecContext(ctx, linkCaseDeclaration, arg.CaseID, arg.DeclarationID, arg.Role)
	return err
}

const linkClueReceipt = `-- name: LinkClueReceipt :exec
INSERT INTO clue_receipts(case_id,clue_id,receipt_id) VALUES (?,?,?)
`

type LinkClueReceiptParams struct {
	CaseID    string
	ClueID    int64
	ReceiptID int64
}

func (q *Queries) LinkClueReceipt(ctx context.Context, arg LinkClueReceiptParams) error {
	_, err := q.db.ExecContext(ctx, linkClueReceipt, arg.CaseID, arg.ClueID, arg.ReceiptID)
	return err
}

const linkCorrelationCase = `-- name: LinkCorrelationCase :exec
INSERT INTO correlation_cases (correlation_id,case_id) VALUES (?,?)
`

type LinkCorrelationCaseParams struct {
	CorrelationID string
	CaseID        string
}

func (q *Queries) LinkCorrelationCase(ctx context.Context, arg LinkCorrelationCaseParams) error {
	_, err := q.db.ExecContext(ctx, linkCorrelationCase, arg.CorrelationID, arg.CaseID)
	return err
}

const linkCorrelationEvidence = `-- name: LinkCorrelationEvidence :exec
INSERT INTO correlation_evidence (correlation_id,case_id,receipt_id) VALUES (?,?,?)
`

type LinkCorrelationEvidenceParams struct {
	CorrelationID string
	CaseID        string
	ReceiptID     int64
}

func (q *Queries) LinkCorrelationEvidence(ctx context.Context, arg LinkCorrelationEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, linkCorrelationEvidence, arg.CorrelationID, arg.CaseID, arg.ReceiptID)
	return err
}

const linkCorrelationRole = `-- name: LinkCorrelationRole :exec
INSERT INTO correlation_role_candidates (correlation_id,candidate_id) VALUES (?,?)
`

type LinkCorrelationRoleParams struct {
	CorrelationID string
	CandidateID   string
}

func (q *Queries) LinkCorrelationRole(ctx context.Context, arg LinkCorrelationRoleParams) error {
	_, err := q.db.ExecContext(ctx, linkCorrelationRole, arg.CorrelationID, arg.CandidateID)
	return err
}

const linkPolicy = `-- name: LinkPolicy :exec
INSERT INTO case_policy_reviews(case_id,ordinal,policy_id) VALUES (?,?,?)
`

type LinkPolicyParams struct {
	CaseID   string
	Ordinal  int64
	PolicyID string
}

func (q *Queries) LinkPolicy(ctx context.Context, arg LinkPolicyParams) error {
	_, err := q.db.ExecContext(ctx, linkPolicy, arg.CaseID, arg.Ordinal, arg.PolicyID)
	return err
}

const linkRoleCase = `-- name: LinkRoleCase :exec
INSERT INTO role_candidate_case_links (candidate_id,case_id) VALUES (?,?)
`

type LinkRoleCaseParams struct {
	CandidateID string
	CaseID      string
}

func (q *Queries) LinkRoleCase(ctx context.Context, arg LinkRoleCaseParams) error {
	_, err := q.db.ExecContext(ctx, linkRoleCase, arg.CandidateID, arg.CaseID)
	return err
}

const reportIdentity = `-- name: ReportIdentity :one
SELECT COUNT(*) AS report_count,CAST(COALESCE(MAX(schema_version),0) AS INTEGER) AS schema_version FROM report
`

type ReportIdentityRow struct {
	ReportCount   int64
	SchemaVersion int64
}

func (q *Queries) ReportIdentity(ctx context.Context) (ReportIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, reportIdentity)
	var i ReportIdentityRow
	err := row.Scan(&i.ReportCount, &i.SchemaVersion)
	return i, err
}

const summaryAdvisories = `-- name: SummaryAdvisories :many
SELECT id,kind,subject,lead,limits FROM advisory_groups ORDER BY kind,id
`

func (q *Queries) SummaryAdvisories(ctx context.Context) ([]AdvisoryGroup, error) {
	rows, err := q.db.QueryContext(ctx, summaryAdvisories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvisoryGroup
	for rows.Next() {
		var i AdvisoryGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Subject,
			&i.Lead,
			&i.Limits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryCases = `-- name: SummaryCases :many
SELECT c.id,c.smell,d.symbol,f.path,c.start_line,c.end_line,c.verdict,c.suppressed
FROM cases c JOIN declarations d ON d.id=c.primary_declaration_id
JOIN files f ON f.id=d.file_id ORDER BY c.ordinal
`

type SummaryCasesRow struct {
	ID         string
	Smell      string
	Symbol     string
	Path       string
	StartLine  int64
	EndLine    int64
	Verdict    string
	Suppressed int64
}

func (q *Queries) SummaryCases(ctx context.Context) ([]SummaryCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryCasesRow
	for rows.Next() {
		var i SummaryCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Smell,
			&i.Symbol,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.Verdict,
			&i.Suppressed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryClueSets = `-- name: SummaryClueSets :many
SELECT c.kind,c.subject,v.value,v.ordinal,c.ordinal AS clue_ordinal
FROM clues c JOIN clue_values v ON v.clue_id=c.id
WHERE c.case_id=?1 AND c.kind IN ('variant-set','repeated-variant-set','selected-role','selected-implementation-set','selected-message-set')
ORDER BY c.ordinal,v.ordinal
`

type SummaryClueSetsParams struct {
	CaseID string
}

type SummaryClueSetsRow struct {
	Kind        string
	Subject     string
	Value       string
	Ordinal     int64
	ClueOrdinal int64
}

func (q *Queries) SummaryClueSets(ctx context.Context, arg SummaryClueSetsParams) ([]SummaryClueSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryClueSets, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryClueSetsRow
	for rows.Next() {
		var i SummaryClueSetsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Subject,
			&i.Value,
			&i.Ordinal,
			&i.ClueOrdinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryCorrelationCases = `-- name: SummaryCorrelationCases :many
SELECT c.id,c.suppressed,c.verdict FROM correlation_cases cc JOIN cases c ON c.id=cc.case_id WHERE cc.correlation_id=?1 ORDER BY c.id
`

type SummaryCorrelationCasesParams struct {
	CorrelationID string
}

type SummaryCorrelationCasesRow struct {
	ID         string
	Suppressed int64
	Verdict    string
}

func (q *Queries) SummaryCorrelationCases(ctx context.Context, arg SummaryCorrelationCasesParams) ([]SummaryCorrelationCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryCorrelationCases, arg.CorrelationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryCorrelationCasesRow
	for rows.Next() {
		var i SummaryCorrelationCasesRow
		if err := rows.Scan(&i.ID, &i.Suppressed, &i.Verdict); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryCorrelationGuidance = `-- name: SummaryCorrelationGuidance :many
SELECT kind,text FROM correlation_guidance WHERE correlation_id=?1 ORDER BY kind,ordinal
`

type SummaryCorrelationGuidanceParams struct {
	CorrelationID string
}

type SummaryCorrelationGuidanceRow struct {
	Kind string
	Text string
}

func (q *Queries) SummaryCorrelationGuidance(ctx context.Context, arg SummaryCorrelationGuidanceParams) ([]SummaryCorrelationGuidanceRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryCorrelationGuidance, arg.CorrelationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryCorrelationGuidanceRow
	for rows.Next() {
		var i SummaryCorrelationGuidanceRow
		if err := rows.Scan(&i.Kind, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryCorrelationMappings = `-- name: SummaryCorrelationMappings :many
SELECT DISTINCT r.subject AS variant,r.spelling AS implementation FROM correlation_evidence ce JOIN source_receipts r ON r.id=ce.receipt_id AND r.case_id=ce.case_id WHERE ce.correlation_id=?1 AND r.kind='selection-variant-mapping' ORDER BY r.subject,r.spelling
`

type SummaryCorrelationMappingsParams struct {
	CorrelationID string
}

type SummaryCorrelationMappingsRow struct {
	Variant        string
	Implementation string
}

func (q *Queries) SummaryCorrelationMappings(ctx context.Context, arg SummaryCorrelationMappingsParams) ([]SummaryCorrelationMappingsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryCorrelationMappings, arg.CorrelationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryCorrelationMappingsRow
	for rows.Next() {
		var i SummaryCorrelationMappingsRow
		if err := rows.Scan(&i.Variant, &i.Implementation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryCorrelationPlayers = `-- name: SummaryCorrelationPlayers :many
SELECT DISTINCT p.identity FROM correlation_role_candidates cr JOIN role_candidate_implementations p ON p.candidate_id=cr.candidate_id WHERE cr.correlation_id=?1 ORDER BY p.identity
`

type SummaryCorrelationPlayersParams struct {
	CorrelationID string
}

func (q *Queries) SummaryCorrelationPlayers(ctx context.Context, arg SummaryCorrelationPlayersParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, summaryCorrelationPlayers, arg.CorrelationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var identity string
		if err := rows.Scan(&identity); err != nil {
			return nil, err
		}
		items = append(items, identity)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryCorrelationRoles = `-- name: SummaryCorrelationRoles :many
SELECT r.id,r.canonical_interface FROM correlation_role_candidates cr JOIN role_candidates r ON r.id=cr.candidate_id WHERE cr.correlation_id=?1 ORDER BY r.id
`

type SummaryCorrelationRolesParams struct {
	CorrelationID string
}

type SummaryCorrelationRolesRow struct {
	ID                 string
	CanonicalInterface string
}

func (q *Queries) SummaryCorrelationRoles(ctx context.Context, arg SummaryCorrelationRolesParams) ([]SummaryCorrelationRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryCorrelationRoles, arg.CorrelationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryCorrelationRolesRow
	for rows.Next() {
		var i SummaryCorrelationRolesRow
		if err := rows.Scan(&i.ID, &i.CanonicalInterface); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryCorrelations = `-- name: SummaryCorrelations :many
SELECT id, kind, confidence, variant_domain, diagnosis, policy_id, policy_status, policy_note, review_prompt FROM correlations ORDER BY id
`

func (q *Queries) SummaryCorrelations(ctx context.Context) ([]Correlation, error) {
	rows, err := q.db.QueryContext(ctx, summaryCorrelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Correlation
	for rows.Next() {
		var i Correlation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Confidence,
			&i.VariantDomain,
			&i.Diagnosis,
			&i.PolicyID,
			&i.PolicyStatus,
			&i.PolicyNote,
			&i.ReviewPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryDuplicateFragments = `-- name: SummaryDuplicateFragments :many
SELECT f.path, r.start_line, r.end_line, r.start_offset, r.end_offset
FROM source_receipts r JOIN files f ON f.id = r.file_id
WHERE r.case_id = ?1 AND r.kind = 'duplicate-fragment'
ORDER BY f.path, r.start_offset, r.end_offset
`

type SummaryDuplicateFragmentsParams struct {
	CaseID string
}

type SummaryDuplicateFragmentsRow struct {
	Path        string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
}

func (q *Queries) SummaryDuplicateFragments(ctx context.Context, arg SummaryDuplicateFragmentsParams) ([]SummaryDuplicateFragmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryDuplicateFragments, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryDuplicateFragmentsRow
	for rows.Next() {
		var i SummaryDuplicateFragmentsRow
		if err := rows.Scan(
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.StartOffset,
			&i.EndOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryMetrics = `-- name: SummaryMetrics :many
SELECT kind,subject,numeric_value,limit_value,operator FROM clues
WHERE case_id=? AND numeric_value IS NOT NULL ORDER BY ordinal
`

type SummaryMetricsParams struct {
	CaseID string
}

type SummaryMetricsRow struct {
	Kind         string
	Subject      string
	NumericValue interface{}
	LimitValue   interface{}
	Operator     *string
}

func (q *Queries) SummaryMetrics(ctx context.Context, arg SummaryMetricsParams) ([]SummaryMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryMetrics, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryMetricsRow
	for rows.Next() {
		var i SummaryMetricsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Subject,
			&i.NumericValue,
			&i.LimitValue,
			&i.Operator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryPolicy = `-- name: SummaryPolicy :many
SELECT p.id,p.note,p.review_prompt FROM case_policy_reviews cp
JOIN policy_reviews p ON p.id=cp.policy_id WHERE cp.case_id=? ORDER BY cp.ordinal
`

type SummaryPolicyParams struct {
	CaseID string
}

func (q *Queries) SummaryPolicy(ctx context.Context, arg SummaryPolicyParams) ([]PolicyReview, error) {
	rows, err := q.db.QueryContext(ctx, summaryPolicy, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyReview
	for rows.Next() {
		var i PolicyReview
		if err := rows.Scan(&i.ID, &i.Note, &i.ReviewPrompt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryRoleInterfaces = `-- name: SummaryRoleInterfaces :many
SELECT identity,relationship FROM role_candidate_interfaces WHERE candidate_id=?1 ORDER BY relationship,identity
`

type SummaryRoleInterfacesParams struct {
	CandidateID string
}

type SummaryRoleInterfacesRow struct {
	Identity     string
	Relationship string
}

func (q *Queries) SummaryRoleInterfaces(ctx context.Context, arg SummaryRoleInterfacesParams) ([]SummaryRoleInterfacesRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryRoleInterfaces, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryRoleInterfacesRow
	for rows.Next() {
		var i SummaryRoleInterfacesRow
		if err := rows.Scan(&i.Identity, &i.Relationship); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryRoles = `-- name: SummaryRoles :many
SELECT id,canonical_interface,confidence,classification FROM role_candidates ORDER BY id
`

func (q *Queries) SummaryRoles(ctx context.Context) ([]RoleCandidate, error) {
	rows, err := q.db.QueryContext(ctx, summaryRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleCandidate
	for rows.Next() {
		var i RoleCandidate
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalInterface,
			&i.Confidence,
			&i.Classification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarySelectionReceipts = `-- name: SummarySelectionReceipts :many
SELECT r.kind,r.subject,f.path,r.start_line,r.end_line,r.start_offset,r.end_offset
FROM source_receipts r JOIN files f ON f.id=r.file_id
WHERE r.case_id=?1 AND r.kind IN ('selection-decision','selection-origin','selection-flow','selected-message')
ORDER BY f.path,r.start_offset,r.kind
`

type SummarySelectionReceiptsParams struct {
	CaseID string
}

type SummarySelectionReceiptsRow struct {
	Kind        string
	Subject     string
	Path        string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
}

func (q *Queries) SummarySelectionReceipts(ctx context.Context, arg SummarySelectionReceiptsParams) ([]SummarySelectionReceiptsRow, error) {
	rows, err := q.db.QueryContext(ctx, summarySelectionReceipts, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarySelectionReceiptsRow
	for rows.Next() {
		var i SummarySelectionReceiptsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Subject,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.StartOffset,
			&i.EndOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarySuppressions = `-- name: SummarySuppressions :many
SELECT f.path,s.line,s.justification FROM suppressions s
JOIN files f ON f.id=s.file_id WHERE s.case_id=? ORDER BY s.ordinal
`

type SummarySuppressionsParams struct {
	CaseID *string
}

type SummarySuppressionsRow struct {
	Path          string
	Line          int64
	Justification string
}

func (q *Queries) SummarySuppressions(ctx context.Context, arg SummarySuppressionsParams) ([]SummarySuppressionsRow, error) {
	rows, err := q.db.QueryContext(ctx, summarySuppressions, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarySuppressionsRow
	for rows.Next() {
		var i SummarySuppressionsRow
		if err := rows.Scan(&i.Path, &i.Line, &i.Justification); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryTotals = `-- name: SummaryTotals :one
SELECT CAST(failed AS INTEGER) AS failed,CAST(warned AS INTEGER) AS warned,CAST(suppressed AS INTEGER) AS suppressed FROM summary
`

type SummaryTotalsRow struct {
	Failed     int64
	Warned     int64
	Suppressed int64
}

func (q *Queries) SummaryTotals(ctx context.Context) (SummaryTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, summaryTotals)
	var i SummaryTotalsRow
	err := row.Scan(&i.Failed, &i.Warned, &i.Suppressed)
	return i, err
}

const summaryVariantDecisions = `-- name: SummaryVariantDecisions :many
SELECT f.path,r.start_line,r.end_line,r.start_offset,r.end_offset,d.symbol
FROM source_receipts r JOIN files f ON f.id=r.file_id
JOIN declarations d ON d.id=r.source_declaration_id
WHERE r.case_id=?1 AND r.kind='variant-decision'
ORDER BY f.path,r.start_offset
`

type SummaryVariantDecisionsParams struct {
	CaseID string
}

type SummaryVariantDecisionsRow struct {
	Path        string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
	Symbol      string
}

func (q *Queries) SummaryVariantDecisions(ctx context.Context, arg SummaryVariantDecisionsParams) ([]SummaryVariantDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryVariantDecisions, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryVariantDecisionsRow
	for rows.Next() {
		var i SummaryVariantDecisionsRow
		if err := rows.Scan(
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.StartOffset,
			&i.EndOffset,
			&i.Symbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryWarnings = `-- name: SummaryWarnings :many
SELECT code,COALESCE(f.path,''),w.line,w.message FROM warnings w
LEFT JOIN files f ON f.id=w.file_id ORDER BY w.ordinal
`

type SummaryWarningsRow struct {
	Code    string
	Path    string
	Line    int64
	Message string
}

func (q *Queries) SummaryWarnings(ctx context.Context) ([]SummaryWarningsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryWarnings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryWarningsRow
	for rows.Next() {
		var i SummaryWarningsRow
		if err := rows.Scan(
			&i.Code,
			&i.Path,
			&i.Line,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const warningMessages = `-- name: WarningMessages :many
SELECT message FROM warnings ORDER BY ordinal
`

func (q *Queries) WarningMessages(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, warningMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
