// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package snapshotdb

import (
	"context"
)

type Querier interface {
	ActiveStageAdvisories(ctx context.Context) ([]AdvisoryGroup, error)
	AdvisoryCoverage(ctx context.Context) ([]AdvisoryCollector, error)
	AdvisoryReceipts(ctx context.Context, arg AdvisoryReceiptsParams) ([]AdvisoryReceiptsRow, error)
	AdvisorySites(ctx context.Context, arg AdvisorySitesParams) ([]AdvisorySitesRow, error)
	AdvisoryValues(ctx context.Context, arg AdvisoryValuesParams) ([]AdvisoryValuesRow, error)
	DependencyScored(ctx context.Context, arg DependencyScoredParams) (int64, error)
	InsertAdvisoryCollector(ctx context.Context, arg InsertAdvisoryCollectorParams) error
	InsertAdvisoryGroup(ctx context.Context, arg InsertAdvisoryGroupParams) error
	InsertAdvisoryReceipt(ctx context.Context, arg InsertAdvisoryReceiptParams) error
	InsertAdvisorySite(ctx context.Context, arg InsertAdvisorySiteParams) error
	InsertAdvisorySiteValue(ctx context.Context, arg InsertAdvisorySiteValueParams) error
	InsertAdvisoryValue(ctx context.Context, arg InsertAdvisoryValueParams) error
	InsertCase(ctx context.Context, arg InsertCaseParams) error
	InsertClue(ctx context.Context, arg InsertClueParams) (int64, error)
	InsertClueValue(ctx context.Context, arg InsertClueValueParams) error
	InsertCluster(ctx context.Context, arg InsertClusterParams) (int64, error)
	InsertClusterMember(ctx context.Context, arg InsertClusterMemberParams) (int64, error)
	InsertCommit(ctx context.Context, arg InsertCommitParams) error
	InsertCorrelation(ctx context.Context, arg InsertCorrelationParams) error
	InsertCorrelationGuidance(ctx context.Context, arg InsertCorrelationGuidanceParams) error
	InsertDeclaration(ctx context.Context, arg InsertDeclarationParams) (int64, error)
	InsertDeclarationDependency(ctx context.Context, arg InsertDeclarationDependencyParams) error
	InsertDependency(ctx context.Context, arg InsertDependencyParams) (int64, error)
	InsertDependencyReceipt(ctx context.Context, arg InsertDependencyReceiptParams) error
	InsertExpansionDeclaration(ctx context.Context, arg InsertExpansionDeclarationParams) error
	InsertExpansionSite(ctx context.Context, arg InsertExpansionSiteParams) error
	InsertFile(ctx context.Context, arg InsertFileParams) (int64, error)
	InsertGuidance(ctx context.Context, arg InsertGuidanceParams) error
	InsertHistory(ctx context.Context, arg InsertHistoryParams) error
	InsertHistoryFile(ctx context.Context, arg InsertHistoryFileParams) error
	InsertPolicy(ctx context.Context, arg InsertPolicyParams) error
	InsertReport(ctx context.Context, arg InsertReportParams) error
	InsertRoleCandidate(ctx context.Context, arg InsertRoleCandidateParams) error
	InsertRoleImplementation(ctx context.Context, arg InsertRoleImplementationParams) error
	InsertRoleInterface(ctx context.Context, arg InsertRoleInterfaceParams) error
	InsertRoleMessage(ctx context.Context, arg InsertRoleMessageParams) error
	InsertRoleReceipt(ctx context.Context, arg InsertRoleReceiptParams) error
	InsertSourceReceipt(ctx context.Context, arg InsertSourceReceiptParams) (int64, error)
	InsertStage(ctx context.Context, arg InsertStageParams) error
	InsertStageCollector(ctx context.Context, arg InsertStageCollectorParams) error
	InsertSuppression(ctx context.Context, arg InsertSuppressionParams) error
	InsertWarning(ctx context.Context, arg InsertWarningParams) error
	LinkCaseDeclaration(ctx context.Context, arg LinkCaseDeclarationParams) error
	LinkClueReceipt(ctx context.Context, arg LinkClueReceiptParams) error
	LinkCorrelationCase(ctx context.Context, arg LinkCorrelationCaseParams) error
	LinkCorrelationEvidence(ctx context.Context, arg LinkCorrelationEvidenceParams) error
	LinkCorrelationRole(ctx context.Context, arg LinkCorrelationRoleParams) error
	LinkPolicy(ctx context.Context, arg LinkPolicyParams) error
	LinkRoleCase(ctx context.Context, arg LinkRoleCaseParams) error
	ReportIdentity(ctx context.Context) (ReportIdentityRow, error)
	StageCollectors(ctx context.Context, arg StageCollectorsParams) ([]StageCollector, error)
	SummaryAdvisories(ctx context.Context) ([]AdvisoryGroup, error)
	SummaryCases(ctx context.Context) ([]SummaryCasesRow, error)
	SummaryClueSets(ctx context.Context, arg SummaryClueSetsParams) ([]SummaryClueSetsRow, error)
	SummaryCorrelationCases(ctx context.Context, arg SummaryCorrelationCasesParams) ([]SummaryCorrelationCasesRow, error)
	SummaryCorrelationGuidance(ctx context.Context, arg SummaryCorrelationGuidanceParams) ([]SummaryCorrelationGuidanceRow, error)
	SummaryCorrelationMappings(ctx context.Context, arg SummaryCorrelationMappingsParams) ([]SummaryCorrelationMappingsRow, error)
	SummaryCorrelationPlayers(ctx context.Context, arg SummaryCorrelationPlayersParams) ([]string, error)
	SummaryCorrelationRoles(ctx context.Context, arg SummaryCorrelationRolesParams) ([]SummaryCorrelationRolesRow, error)
	SummaryCorrelations(ctx context.Context) ([]Correlation, error)
	SummaryDuplicateFragments(ctx context.Context, arg SummaryDuplicateFragmentsParams) ([]SummaryDuplicateFragmentsRow, error)
	SummaryMetrics(ctx context.Context, arg SummaryMetricsParams) ([]SummaryMetricsRow, error)
	SummaryPolicy(ctx context.Context, arg SummaryPolicyParams) ([]PolicyReview, error)
	SummaryRoleInterfaces(ctx context.Context, arg SummaryRoleInterfacesParams) ([]SummaryRoleInterfacesRow, error)
	SummaryRoles(ctx context.Context) ([]RoleCandidate, error)
	SummarySelectionReceipts(ctx context.Context, arg SummarySelectionReceiptsParams) ([]SummarySelectionReceiptsRow, error)
	SummaryStages(ctx context.Context) ([]RefactoringStage, error)
	SummarySuppressions(ctx context.Context, arg SummarySuppressionsParams) ([]SummarySuppressionsRow, error)
	SummaryTotals(ctx context.Context) (SummaryTotalsRow, error)
	SummaryVariantDecisions(ctx context.Context, arg SummaryVariantDecisionsParams) ([]SummaryVariantDecisionsRow, error)
	SummaryWarnings(ctx context.Context) ([]SummaryWarningsRow, error)
	WarningMessages(ctx context.Context) ([]string, error)
}

var _ Querier = (*Queries)(nil)
