// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package snapshotdb

import (
	"context"
)

const dependencyScored = `-- name: DependencyScored :one
SELECT scored FROM declaration_dependencies WHERE declaration_id=? AND dependency_id=?
`

type DependencyScoredParams struct {
	DeclarationID int64
	DependencyID  int64
}

func (q *Queries) DependencyScored(ctx context.Context, arg DependencyScoredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dependencyScored, arg.DeclarationID, arg.DependencyID)
	var scored int64
	err := row.Scan(&scored)
	return scored, err
}

const insertCase = `-- name: InsertCase :exec
INSERT INTO cases(id,ordinal,primary_declaration_id,smell,verdict,suppressed,start_line,end_line,why,diagnosis) VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertCaseParams struct {
	ID                   string
	Ordinal              int64
	PrimaryDeclarationID int64
	Smell                string
	Verdict              string
	Suppressed           int64
	StartLine            int64
	EndLine              int64
	Why                  string
	Diagnosis            string
}

func (q *Queries) InsertCase(ctx context.Context, arg InsertCaseParams) error {
	_, err := q.db.ExecContext(ctx, insertCase,
		arg.ID,
		arg.Ordinal,
		arg.PrimaryDeclarationID,
		arg.Smell,
		arg.Verdict,
		arg.Suppressed,
		arg.StartLine,
		arg.EndLine,
		arg.Why,
		arg.Diagnosis,
	)
	return err
}

const insertClue = `-- name: InsertClue :execlastid
INSERT INTO clues(case_id,ordinal,kind,subject,value_type,numeric_value,limit_type,limit_value,operator,declaration_id,cluster_id,member_id,pair_left_member_id,pair_right_member_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertClueParams struct {
	CaseID            string
	Ordinal           int64
	Kind              string
	Subject           string
	ValueType         string
	NumericValue      interface{}
	LimitType         *string
	LimitValue        interface{}
	Operator          *string
	DeclarationID     *int64
	ClusterID         *int64
	MemberID          *int64
	PairLeftMemberID  *int64
	PairRightMemberID *int64
}

func (q *Queries) InsertClue(ctx context.Context, arg InsertClueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertClue,
		arg.CaseID,
		arg.Ordinal,
		arg.Kind,
		arg.Subject,
		arg.ValueType,
		arg.NumericValue,
		arg.LimitType,
		arg.LimitValue,
		arg.Operator,
		arg.DeclarationID,
		arg.ClusterID,
		arg.MemberID,
		arg.PairLeftMemberID,
		arg.PairRightMemberID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertClueValue = `-- name: InsertClueValue :exec
INSERT INTO clue_values(clue_id,ordinal,value) VALUES (?,?,?)
`

type InsertClueValueParams struct {
	ClueID  int64
	Ordinal int64
	Value   string
}

func (q *Queries) InsertClueValue(ctx context.Context, arg InsertClueValueParams) error {
	_, err := q.db.ExecContext(ctx, insertClueValue, arg.ClueID, arg.Ordinal, arg.Value)
	return err
}

const insertCluster = `-- name: InsertCluster :execlastid
INSERT INTO clusters(case_id,cluster_key,owner_declaration_id,file_id,ordinal) VALUES (?,?,?,?,?)
`

type InsertClusterParams struct {
	CaseID             string
	ClusterKey         string
	OwnerDeclarationID int64
	FileID             int64
	Ordinal            int64
}

func (q *Queries) InsertCluster(ctx context.Context, arg InsertClusterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCluster,
		arg.CaseID,
		arg.ClusterKey,
		arg.OwnerDeclarationID,
		arg.FileID,
		arg.Ordinal,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertClusterMember = `-- name: InsertClusterMember :execlastid
INSERT INTO cluster_members(cluster_id,case_id,helper_declaration_id,ordinal,call_offset) VALUES (?,?,?,?,?)
`

type InsertClusterMemberParams struct {
	ClusterID           int64
	CaseID              string
	HelperDeclarationID int64
	Ordinal             int64
	CallOffset          int64
}

func (q *Queries) InsertClusterMember(ctx context.Context, arg InsertClusterMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertClusterMember,
		arg.ClusterID,
		arg.CaseID,
		arg.HelperDeclarationID,
		arg.Ordinal,
		arg.CallOffset,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertCommit = `-- name: InsertCommit :exec
INSERT INTO commits(hash,committed_at) VALUES (?,?)
`

type InsertCommitParams struct {
	Hash        string
	CommittedAt int64
}

func (q *Queries) InsertCommit(ctx context.Context, arg InsertCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertCommit, arg.Hash, arg.CommittedAt)
	return err
}

const insertDeclaration = `-- name: InsertDeclaration :execlastid
INSERT INTO declarations(file_id,symbol,start_line,end_line,start_offset,end_offset) VALUES (?,?,?,?,?,?)
`

type InsertDeclarationParams struct {
	FileID      int64
	Symbol      string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
}

func (q *Queries) InsertDeclaration(ctx context.Context, arg InsertDeclarationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDeclaration,
		arg.FileID,
		arg.Symbol,
		arg.StartLine,
		arg.EndLine,
		arg.StartOffset,
		arg.EndOffset,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertDeclarationDependency = `-- name: InsertDeclarationDependency :exec
INSERT INTO declaration_dependencies(declaration_id,dependency_id,scored) VALUES (?,?,?)
`

type InsertDeclarationDependencyParams struct {
	DeclarationID int64
	DependencyID  int64
	Scored        int64
}

func (q *Queries) InsertDeclarationDependency(ctx context.Context, arg InsertDeclarationDependencyParams) error {
	_, err := q.db.ExecContext(ctx, insertDeclarationDependency, arg.DeclarationID, arg.DependencyID, arg.Scored)
	return err
}

const insertDependency = `-- name: InsertDependency :execlastid
INSERT INTO dependencies(identity) VALUES (?)
`

type InsertDependencyParams struct {
	Identity string
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDependency, arg.Identity)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertDependencyReceipt = `-- name: InsertDependencyReceipt :exec
INSERT INTO dependency_receipts(declaration_id,dependency_id,receipt_id,case_id) VALUES (?,?,?,?)
`

type InsertDependencyReceiptParams struct {
	DeclarationID int64
	DependencyID  int64
	ReceiptID     int64
	CaseID        string
}

func (q *Queries) InsertDependencyReceipt(ctx context.Context, arg InsertDependencyReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertDependencyReceipt,
		arg.DeclarationID,
		arg.DependencyID,
		arg.ReceiptID,
		arg.CaseID,
	)
	return err
}

const insertExpansionDeclaration = `-- name: InsertExpansionDeclaration :exec
INSERT INTO receipt_expansion_declarations(receipt_id,ordinal,declaration_id,symbol) VALUES (?,?,?,?)
`

type InsertExpansionDeclarationParams struct {
	ReceiptID     int64
	Ordinal       int64
	DeclarationID int64
	Symbol        string
}

func (q *Queries) InsertExpansionDeclaration(ctx context.Context, arg InsertExpansionDeclarationParams) error {
	_, err := q.db.ExecContext(ctx, insertExpansionDeclaration,
		arg.ReceiptID,
		arg.Ordinal,
		arg.DeclarationID,
		arg.Symbol,
	)
	return err
}

const insertExpansionSite = `-- name: InsertExpansionSite :exec
INSERT INTO receipt_expansion_sites(receipt_id,ordinal,file_id,call_offset,owner_declaration_id) VALUES (?,?,?,?,?)
`

type InsertExpansionSiteParams struct {
	ReceiptID          int64
	Ordinal            int64
	FileID             int64
	CallOffset         int64
	OwnerDeclarationID *int64
}

func (q *Queries) InsertExpansionSite(ctx context.Context, arg InsertExpansionSiteParams) error {
	_, err := q.db.ExecContext(ctx, insertExpansionSite,
		arg.ReceiptID,
		arg.Ordinal,
		arg.FileID,
		arg.CallOffset,
		arg.OwnerDeclarationID,
	)
	return err
}

const insertFile = `-- name: InsertFile :execlastid
INSERT INTO files(path) VALUES (?)
`

type InsertFileParams struct {
	Path string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertFile, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertGuidance = `-- name: InsertGuidance :exec
INSERT INTO case_guidance(case_id,kind,ordinal,item) VALUES (?,?,?,?)
`

type InsertGuidanceParams struct {
	CaseID  string
	Kind    string
	Ordinal int64
	Item    string
}

func (q *Queries) InsertGuidance(ctx context.Context, arg InsertGuidanceParams) error {
	_, err := q.db.ExecContext(ctx, insertGuidance,
		arg.CaseID,
		arg.Kind,
		arg.Ordinal,
		arg.Item,
	)
	return err
}

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO case_history(case_id,ordinal,commit_hash,kind) VALUES (?,?,?,?)
`

type InsertHistoryParams struct {
	CaseID     string
	Ordinal    int64
	CommitHash string
	Kind       string
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertHistory,
		arg.CaseID,
		arg.Ordinal,
		arg.CommitHash,
		arg.Kind,
	)
	return err
}

const insertHistoryFile = `-- name: InsertHistoryFile :exec
INSERT INTO case_history_files(case_id,history_ordinal,ordinal,file_id) VALUES (?,?,?,?)
`

type InsertHistoryFileParams struct {
	CaseID         string
	HistoryOrdinal int64
	Ordinal        int64
	FileID         int64
}

func (q *Queries) InsertHistoryFile(ctx context.Context, arg InsertHistoryFileParams) error {
	_, err := q.db.ExecContext(ctx, insertHistoryFile,
		arg.CaseID,
		arg.HistoryOrdinal,
		arg.Ordinal,
		arg.FileID,
	)
	return err
}

const insertPolicy = `-- name: InsertPolicy :exec
INSERT INTO policy_reviews(id,note,review_prompt) VALUES (?,?,?)
`

type InsertPolicyParams struct {
	ID           string
	Note         string
	ReviewPrompt string
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) error {
	_, err := q.db.ExecContext(ctx, insertPolicy, arg.ID, arg.Note, arg.ReviewPrompt)
	return err
}

const insertReport = `-- name: InsertReport :exec
INSERT INTO report(id,schema_version,columbo_version) VALUES (1, ?, ?)
`

type InsertReportParams struct {
	SchemaVersion  int64
	ColumboVersion string
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.ExecContext(ctx, insertReport, arg.SchemaVersion, arg.ColumboVersion)
	return err
}

const insertSourceReceipt = `-- name: InsertSourceReceipt :execlastid
INSERT INTO source_receipts(case_id,ordinal,kind,file_id,start_line,end_line,start_offset,end_offset,subject,value_type,value,nesting,source_declaration_id,spelling) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertSourceReceiptParams struct {
	CaseID              string
	Ordinal             int64
	Kind                string
	FileID              int64
	StartLine           int64
	EndLine             int64
	StartOffset         int64
	EndOffset           int64
	Subject             string
	ValueType           *string
	Value               interface{}
	Nesting             *int64
	SourceDeclarationID *int64
	Spelling            string
}

func (q *Queries) InsertSourceReceipt(ctx context.Context, arg InsertSourceReceiptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSourceReceipt,
		arg.CaseID,
		arg.Ordinal,
		arg.Kind,
		arg.FileID,
		arg.StartLine,
		arg.EndLine,
		arg.StartOffset,
		arg.EndOffset,
		arg.Subject,
		arg.ValueType,
		arg.Value,
		arg.Nesting,
		arg.SourceDeclarationID,
		arg.Spelling,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertSuppression = `-- name: InsertSuppression :exec
INSERT INTO suppressions(ordinal,smell,symbol,file_id,line,justification,applied,case_id) VALUES (?,?,?,?,?,?,?,?)
`

type InsertSuppressionParams struct {
	Ordinal       int64
	Smell         string
	Symbol        string
	FileID        int64
	Line          int64
	Justification string
	Applied       int64
	CaseID        *string
}

func (q *Queries) InsertSuppression(ctx context.Context, arg InsertSuppressionParams) error {
	_, err := q.db.ExecContext(ctx, insertSuppression,
		arg.Ordinal,
		arg.Smell,
		arg.Symbol,
		arg.FileID,
		arg.Line,
		arg.Justification,
		arg.Applied,
		arg.CaseID,
	)
	return err
}

const insertWarning = `-- name: InsertWarning :exec
INSERT INTO warnings(ordinal,code,file_id,line,message) VALUES (?,?,?,?,?)
`

type InsertWarningParams struct {
	Ordinal int64
	Code    string
	FileID  *int64
	Line    int64
	Message string
}

func (q *Queries) InsertWarning(ctx context.Context, arg InsertWarningParams) error {
	_, err := q.db.ExecContext(ctx, insertWarning,
		arg.Ordinal,
		arg.Code,
		arg.FileID,
		arg.Line,
		arg.Message,
	)
	return err
}

const linkCaseDeclaration = `-- name: LinkCaseDeclaration :exec
INSERT OR IGNORE INTO case_declarations(case_id,declaration_id,role) VALUES (?,?,?)
`

type LinkCaseDeclarationParams struct {
	CaseID        string
	DeclarationID int64
	Role          string
}

func (q *Queries) LinkCaseDeclaration(ctx context.Context, arg LinkCaseDeclarationParams) error {
	_, err := q.db.ExecContext(ctx, linkCaseDeclaration, arg.CaseID, arg.DeclarationID, arg.Role)
	return err
}

const linkClueReceipt = `-- name: LinkClueReceipt :exec
INSERT INTO clue_receipts(case_id,clue_id,receipt_id) VALUES (?,?,?)
`

type LinkClueReceiptParams struct {
	CaseID    string
	ClueID    int64
	ReceiptID int64
}

func (q *Queries) LinkClueReceipt(ctx context.Context, arg LinkClueReceiptParams) error {
	_, err := q.db.ExecContext(ctx, linkClueReceipt, arg.CaseID, arg.ClueID, arg.ReceiptID)
	return err
}

const linkPolicy = `-- name: LinkPolicy :exec
INSERT INTO case_policy_reviews(case_id,ordinal,policy_id) VALUES (?,?,?)
`

type LinkPolicyParams struct {
	CaseID   string
	Ordinal  int64
	PolicyID string
}

func (q *Queries) LinkPolicy(ctx context.Context, arg LinkPolicyParams) error {
	_, err := q.db.ExecContext(ctx, linkPolicy, arg.CaseID, arg.Ordinal, arg.PolicyID)
	return err
}

const reportIdentity = `-- name: ReportIdentity :one
SELECT COUNT(*) AS report_count,CAST(COALESCE(MAX(schema_version),0) AS INTEGER) AS schema_version FROM report
`

type ReportIdentityRow struct {
	ReportCount   int64
	SchemaVersion int64
}

func (q *Queries) ReportIdentity(ctx context.Context) (ReportIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, reportIdentity)
	var i ReportIdentityRow
	err := row.Scan(&i.ReportCount, &i.SchemaVersion)
	return i, err
}

const summaryCases = `-- name: SummaryCases :many
SELECT c.id,c.smell,d.symbol,f.path,c.start_line,c.end_line,c.verdict,c.suppressed
FROM cases c JOIN declarations d ON d.id=c.primary_declaration_id
JOIN files f ON f.id=d.file_id ORDER BY c.ordinal
`

type SummaryCasesRow struct {
	ID         string
	Smell      string
	Symbol     string
	Path       string
	StartLine  int64
	EndLine    int64
	Verdict    string
	Suppressed int64
}

func (q *Queries) SummaryCases(ctx context.Context) ([]SummaryCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryCasesRow
	for rows.Next() {
		var i SummaryCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Smell,
			&i.Symbol,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.Verdict,
			&i.Suppressed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryDuplicateFragments = `-- name: SummaryDuplicateFragments :many
SELECT f.path, r.start_line, r.end_line, r.start_offset, r.end_offset
FROM source_receipts r JOIN files f ON f.id = r.file_id
WHERE r.case_id = ?1 AND r.kind = 'duplicate-fragment'
ORDER BY f.path, r.start_offset, r.end_offset
`

type SummaryDuplicateFragmentsParams struct {
	CaseID string
}

type SummaryDuplicateFragmentsRow struct {
	Path        string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
}

func (q *Queries) SummaryDuplicateFragments(ctx context.Context, arg SummaryDuplicateFragmentsParams) ([]SummaryDuplicateFragmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryDuplicateFragments, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryDuplicateFragmentsRow
	for rows.Next() {
		var i SummaryDuplicateFragmentsRow
		if err := rows.Scan(
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.StartOffset,
			&i.EndOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryMetrics = `-- name: SummaryMetrics :many
SELECT kind,subject,numeric_value,limit_value,operator FROM clues
WHERE case_id=? AND numeric_value IS NOT NULL ORDER BY ordinal
`

type SummaryMetricsParams struct {
	CaseID string
}

type SummaryMetricsRow struct {
	Kind         string
	Subject      string
	NumericValue interface{}
	LimitValue   interface{}
	Operator     *string
}

func (q *Queries) SummaryMetrics(ctx context.Context, arg SummaryMetricsParams) ([]SummaryMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryMetrics, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryMetricsRow
	for rows.Next() {
		var i SummaryMetricsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Subject,
			&i.NumericValue,
			&i.LimitValue,
			&i.Operator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryPolicy = `-- name: SummaryPolicy :many
SELECT p.id,p.note,p.review_prompt FROM case_policy_reviews cp
JOIN policy_reviews p ON p.id=cp.policy_id WHERE cp.case_id=? ORDER BY cp.ordinal
`

type SummaryPolicyParams struct {
	CaseID string
}

func (q *Queries) SummaryPolicy(ctx context.Context, arg SummaryPolicyParams) ([]PolicyReview, error) {
	rows, err := q.db.QueryContext(ctx, summaryPolicy, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyReview
	for rows.Next() {
		var i PolicyReview
		if err := rows.Scan(&i.ID, &i.Note, &i.ReviewPrompt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarySuppressions = `-- name: SummarySuppressions :many
SELECT f.path,s.line,s.justification FROM suppressions s
JOIN files f ON f.id=s.file_id WHERE s.case_id=? ORDER BY s.ordinal
`

type SummarySuppressionsParams struct {
	CaseID *string
}

type SummarySuppressionsRow struct {
	Path          string
	Line          int64
	Justification string
}

func (q *Queries) SummarySuppressions(ctx context.Context, arg SummarySuppressionsParams) ([]SummarySuppressionsRow, error) {
	rows, err := q.db.QueryContext(ctx, summarySuppressions, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarySuppressionsRow
	for rows.Next() {
		var i SummarySuppressionsRow
		if err := rows.Scan(&i.Path, &i.Line, &i.Justification); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryTotals = `-- name: SummaryTotals :one
SELECT CAST(failed AS INTEGER) AS failed,CAST(warned AS INTEGER) AS warned,CAST(suppressed AS INTEGER) AS suppressed FROM summary
`

type SummaryTotalsRow struct {
	Failed     int64
	Warned     int64
	Suppressed int64
}

func (q *Queries) SummaryTotals(ctx context.Context) (SummaryTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, summaryTotals)
	var i SummaryTotalsRow
	err := row.Scan(&i.Failed, &i.Warned, &i.Suppressed)
	return i, err
}

const summaryVariantDecisions = `-- name: SummaryVariantDecisions :many
SELECT f.path,r.start_line,r.end_line,r.start_offset,r.end_offset,d.symbol
FROM source_receipts r JOIN files f ON f.id=r.file_id
JOIN declarations d ON d.id=r.source_declaration_id
WHERE r.case_id=?1 AND r.kind='variant-decision'
ORDER BY f.path,r.start_offset
`

type SummaryVariantDecisionsParams struct {
	CaseID string
}

type SummaryVariantDecisionsRow struct {
	Path        string
	StartLine   int64
	EndLine     int64
	StartOffset int64
	EndOffset   int64
	Symbol      string
}

func (q *Queries) SummaryVariantDecisions(ctx context.Context, arg SummaryVariantDecisionsParams) ([]SummaryVariantDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryVariantDecisions, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryVariantDecisionsRow
	for rows.Next() {
		var i SummaryVariantDecisionsRow
		if err := rows.Scan(
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.StartOffset,
			&i.EndOffset,
			&i.Symbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryVariantSets = `-- name: SummaryVariantSets :many
SELECT c.kind,c.subject,v.value,v.ordinal,c.ordinal AS clue_ordinal
FROM clues c JOIN clue_values v ON v.clue_id=c.id
WHERE c.case_id=?1 AND c.kind IN ('variant-set','repeated-variant-set')
ORDER BY c.ordinal,v.ordinal
`

type SummaryVariantSetsParams struct {
	CaseID string
}

type SummaryVariantSetsRow struct {
	Kind        string
	Subject     string
	Value       string
	Ordinal     int64
	ClueOrdinal int64
}

func (q *Queries) SummaryVariantSets(ctx context.Context, arg SummaryVariantSetsParams) ([]SummaryVariantSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryVariantSets, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryVariantSetsRow
	for rows.Next() {
		var i SummaryVariantSetsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Subject,
			&i.Value,
			&i.Ordinal,
			&i.ClueOrdinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryWarnings = `-- name: SummaryWarnings :many
SELECT code,COALESCE(f.path,''),w.line,w.message FROM warnings w
LEFT JOIN files f ON f.id=w.file_id ORDER BY w.ordinal
`

type SummaryWarningsRow struct {
	Code    string
	Path    string
	Line    int64
	Message string
}

func (q *Queries) SummaryWarnings(ctx context.Context) ([]SummaryWarningsRow, error) {
	rows, err := q.db.QueryContext(ctx, summaryWarnings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryWarningsRow
	for rows.Next() {
		var i SummaryWarningsRow
		if err := rows.Scan(
			&i.Code,
			&i.Path,
			&i.Line,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const warningMessages = `-- name: WarningMessages :many
SELECT message FROM warnings ORDER BY ordinal
`

func (q *Queries) WarningMessages(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, warningMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
