#!/usr/bin/env python3
"""Verify the narrow DB access manifest, never trust generated/nolint comments."""
import argparse
import json
import os
from pathlib import Path
import re
import sys

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
parser.add_argument("--json", type=Path)
args = parser.parse_args()
root = args.root.resolve()
manifest = json.loads((Path(__file__).parent / "manifest.json").read_text())
allowed = {manifest["lifecycle"], *manifest["generated"]}
issues = []
# Go 1.25.1 src/internal/syslist/syslist.go: past/present/future recognized
# filename constraints. Application/test source has no reviewed build variants.
platform_suffixes = set("""aix android darwin dragonfly freebsd hurd illumos ios js
linux nacl netbsd openbsd plan9 solaris wasip1 windows zos 386 amd64 amd64p32 arm
armbe arm64 arm64be loong64 mips mipsle mips64 mips64le mips64p32 mips64p32le ppc
ppc64 ppc64le riscv riscv64 s390 s390x sparc sparc64 wasm""".split())

def report(path, line, text):
    issues.append({"path": path, "line": line, "check": "database-manifest", "message": text})

# Do not follow directory links; reject them before any source can hide behind
# a corpus/tool-tree alias. Corpus roots are explicit reviewed source inventory.
for directory, names, _ in os.walk(root, followlinks=False):
    names[:] = sorted(name for name in names if name not in {".git", ".tools", "vendor"})
    for name in names[:]:
        path = Path(directory) / name
        relative = path.relative_to(root).as_posix()
        if path.is_symlink():
            report(relative, 1, "Source directory symlinks cannot hide database access")
            names.remove(name)
        elif name == "testdata" and not (relative == manifest["analyzer_corpus"] or
                                        relative.startswith(manifest["analyzer_corpus"] + "/")):
            report(relative, 1, "Unreviewed testdata source tree; only the named analyzer corpus is excluded")

for name in sorted(allowed):
    path = root / name
    if not path.is_file() or path.is_symlink():
        report(name, 1, "Required regular boundary file is missing (or is a symlink)")

for path in sorted((root / "internal/snapshotdb").rglob("*.go")):
    name = path.relative_to(root).as_posix()
    if name not in allowed:
        report(name, 1, "Only lifecycle.go and the four exact sqlc outputs may be in snapshotdb")

# Deliberately inspect all Go source, including build-tagged and generated source.
# testdata is an analyzer corpus, not application source; guard fixtures use .txt.
for path in sorted(root.rglob("*.go")):
    relative = path.relative_to(root)
    if any(part in {".git", ".tools", "vendor", "testdata"} for part in relative.parts):
        continue
    name = relative.as_posix()
    if path.is_symlink():
        report(name, 1, "Source symlinks cannot expand a database access exception")
        continue
    stem = path.stem.removesuffix("_test")
    if "_" in stem and stem.rsplit("_", 1)[-1] in platform_suffixes:
        report(name, 1, "Unreviewed source GOOS/GOARCH filename constraint can hide raw SQL from lint")
    text = path.read_text()
    for line, value in enumerate(text.splitlines(), 1):
        if re.search(r'^\s*//(?:go:build\b|\s*\+build\b)', value):
            report(name, line, "Unreviewed source build constraint can hide raw SQL from lint")
        # golangci's nolint filtering and forbidigo's permit directive are not
        # a second way to grant exceptions. Add a reviewed exact-path exception.
        if re.search(r'(?://[\s/]*|/\*\s*)(?:nolint(?::|\b)|permit(?::|\s*\())', value):
            report(name, line, "Inline lint/permit exclusions are forbidden by the database boundary gate")
    if name in manifest["generated"]:
        if not text.startswith("// Code generated by sqlc. DO NOT EDIT.\n"):
            report(name, 1, "Claimed sqlc output lacks the exact generator header; regeneration is also required")

if args.json:
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(issues, indent=2) + "\n")
for issue in issues:
    print(f'{issue["path"]}:{issue["line"]}: {issue["message"]}')
if not issues:
    print("Database boundary file manifest: clean")
sys.exit(bool(issues))
